language: node_js

dist: trusty

matrix:
  include:
  - os: linux
    env: TO_TEST=chrome
    addons:
      apt:
        sources:
        - google-chrome
        packages:
        - google-chrome-stable
  - os: linux
    env: TO_TEST=firefox
    addons:
      firefox: latest
  - os: linux
    env: TO_TEST=node
  - os: linux
    env: TO_TEST=lint
  - os: osx
    env: TO_TEST=safari
    osx_image: xcode8.3

node_js:
- node # latest stable node release

cache: yarn # cache yarn

before_install:
- if [ "$TO_TEST" = "chrome" ]; then export CHROME_BIN=/usr/bin/google-chrome; fi
- if [ "$TO_TEST" = "chrome" ] || [ "$TO_TEST" = "firefox" ]; then export DISPLAY=:99.0; fi
- if [ "$TO_TEST" = "chrome" ] || [ "$TO_TEST" = "firefox" ]; then sh -e /etc/init.d/xvfb start; fi
before_script:
- node_modules/.bin/gulp build
script:
- if [ "$TO_TEST" = "chrome" ]; then node_modules/.bin/karma start --browsers Chrome_travis_ci; fi
- if [ "$TO_TEST" = "firefox" ]; then node_modules/.bin/karma start --browsers Firefox; fi
- if [ "$TO_TEST" = "safari" ]; then node_modules/.bin/karma start --browsers Safari; fi
- if [ "$TO_TEST" = "node" ]; then node_modules/.bin/jasmine; fi
- if [ "$TO_TEST" = "lint" ]; then node_modules/.bin/eslint src/main src/test *.js; fi

notifications:
  slack:
    rooms:
    - secure: BKP7WIZDwqEgORVAqWiqkdBYEy8B1mKdlZP4EukJMxn38PiCKioSV7pQqhtjMh5kefWYYfXpA4OAnulU2EhThXJU5nDiEep26a4VjfCig7km4cizQFyL94ukfiQ7FClB0ECjnpUZO75vYUXRkXAGwDuDiEyGAJc/wQSEGJyl3QXHY60M8emqNfDl6+CB3ijJCqXgVaolY1Sap/1chtcjCYuOIMGtCJWlBMaNOVc6rk/QcblregNtlQEFoEz5cfEAgLRxD5AUxg5ANXbKLxJXezxVj5GEbMS8V+h6iee91gnm9+kNDfzXeM2onx9mtHtowfC+v5NU3H7N9uolXIJMBeqoF6pvZJFGT7Ebi5b97CgJjk9ivn3Iftjm0LRhoqcQRcEKrLoZpCU1zW5FdZDmSi32x2uw2F0r5xpMPr9wkWNLo9GUmFgpGEpiulQi/Ec/NSolCwxGQCOYHTDVLqNXQNKFK2xdypk3qplgeY439XhRFE7UOTU8zTMYrTtXnS28Z+ct4AzeQRza3VhnSO/cmt41iIhp0OTK/2R61RdQTnuAzgNyt/Q1gQD7V27VLIOELck88CUMbgZyB9UT9m3IdXXPD58lQmbWo2tifSaklPudhO18GpIVR0S2QUSsW1VKW6gbP6oVnSCigJw4iDeZkMOGNTUo9fW1lYzdve5F+t0=
    - secure: eH0XKBr6eqqyCeUFCxO8YiXlMbLqJhGCHQUG0m1cSfUGteJy/6+YqrM3TqayUpWwscDmczEB7omH3QEPKcOJBHH/GNc/u3XcZmUwD510sqEtxzXi8zpePksK0uuCoj2ai9jp3stKAD1xsGKlIN2I5KXOCqY6hgVxYYy9PmjL/vinyWR1rPnR/5m9wSDrUDaDBsSPzeUKb9o3hKlUW+DPQ559N+Y5qGMAZAUVJj8uZWlEXMXHYcKqH8hql0QGid9R4JJ2l0bsT1qYdL66/d/HVG3ZJHw//cYUtjRYPq88cJnACblEpB61E3aj76qmF29cr5f+7lBZwNJdqM0F6hjN+GrKv1rdrJuK3xkxVi5rOHBlsDDPOBEvgJJzWwoOEJ9c6rfWnGR9kpCEddkTxR1WBBOz40rY3alMcaqsAJiz4aikjH+Io/YOnAJaW9RfkfbqtiiYTWtXIZnfVkRvLTLTjBG459GJLeupMv7B9OB30g6to4FhLXmVTz2idrapZZYgPW3yac5rNBTXCgbDNbbLzduXUTGSImceh84RYlDXb5g9bBHA+gT5Psbg5Vik3wPzCNdJTg8hgwYB9ujfee9V6FXW/8/eBYcWwKul45mudchraKZRchULP6w68hRBi2d0BjfZ54w9UG0TmGBxtiPk4A4UWL0nEP+q3UnJE5b9C7M=
